import { z } from "zod";

export const clientSchema = z.object({
  id: z.string(),
  name: z.string().min(2, "Client name must be at least 2 characters"),
  code: z.string(),
  email: z.string().email("Invalid email").optional().or(z.literal("")),
  phone: z.string().optional(),
  gstNumber: z.string().optional(),
  industry: z.string(),
  projectCount: z.number().min(0),
  managerName: z.string().optional(),
  managerCode: z.string().optional(),
});

export type Client = z.infer<typeof clientSchema>;

export const createClientFormSchema = clientSchema.omit({
  id: true,
});

export type CreateClientFormValues = z.infer<typeof createClientFormSchema>;

export const SAMPLE_CLIENTS: Client[] = [
  {
    id: "CLI-01",
    name: "Acton Ewing",
    code: "FGD56754",
    email: "xoho@mailinator.com",
    phone: "91 15347835869",
    gstNumber: "",
    industry: "Software",
    projectCount: 2,
    managerName: "Test RUR",
    managerCode: "AILOITTE-73",
  },
  {
    id: "CLI-02",
    name: "Rakesh Client",
    code: "123100",
    email: "",
    phone: "",
    gstNumber: "",
    industry: "Artificial-Intelligence",
    projectCount: 2,
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
  },
  {
    id: "CLI-03",
    name: "Vipul Client",
    code: "890123",
    email: "",
    phone: "",
    gstNumber: "",
    industry: "Software",
    projectCount: 4,
    managerName: "-",
    managerCode: "",
  },
  {
    id: "CLI-04",
    name: "client 3",
    code: "asdfasdf",
    email: "person7@gmail.com",
    phone: "",
    gstNumber: "",
    industry: "Healthcare",
    projectCount: 0,
    managerName: "HR Jay Mishra",
    managerCode: "AILOITTE-47",
  },
  {
    id: "CLI-05",
    name: "Sports Client2",
    code: "SC123456",
    email: "",
    phone: "",
    gstNumber: "",
    industry: "Software",
    projectCount: 2,
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
  },
  {
    id: "CLI-06",
    name: "Testing Client",
    code: "Cli-8754",
    email: "",
    phone: "",
    gstNumber: "27ABCDE1234F1Z5",
    industry: "Telecommunications",
    projectCount: 1,
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
  },
  {
    id: "CLI-07",
    name: "apna",
    code: "asdfweaf",
    email: "",
    phone: "",
    gstNumber: "27ABCDE1234F1Z5",
    industry: "Cybersecurity",
    projectCount: 0,
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
  },
  {
    id: "CLI-08",
    name: "notification client",
    code: "XUROSAFE",
    email: "",
    phone: "",
    gstNumber: "27ABCDE1234F1Z6",
    industry: "Healthcare",
    projectCount: 0,
    managerName: "Vikhayat Singh",
    managerCode: "AILO-50",
  },
  {
    id: "CLI-09",
    name: "Apple",
    code: "App-001",
    email: "aman676@app.com",
    phone: "91 8796456876",
    gstNumber: "27ABCDE1234F1Z4",
    industry: "Software",
    projectCount: 6,
    managerName: "Testing Negi",
    managerCode: "AILOITTE-42",
  },
  {
    id: "CLI-10",
    name: "Dr. Morpin",
    code: "IN-001",
    email: "sweta@morphin@gmail.com",
    phone: "7845896526",
    gstNumber: "",
    industry: "Healthcare",
    projectCount: 5,
    managerName: "Sunil Kumar",
    managerCode: "EMP30",
  },
];
