import { z } from "zod";

export const projectStageSchema = z.enum([
  "New",
  "In Discovery",
  "Sprint Planning",
  "In Development",
  "Completed",
]);
export type ProjectStage = z.infer<typeof projectStageSchema>;

export const createProjectFormSchema = z.object({
  name: z.string().min(2, "Project name must be at least 2 characters"),
  code: z.string().optional(),
  stageGroup: projectStageSchema,
  stage: z.string(),
  periodStart: z.string().min(1, "Start Date is required"),
  periodEnd: z.string().min(1, "End Date is required"),
  managerName: z.string().min(1, "Project Manager is required"),
  managerCode: z.string(),
  managerAvatar: z.string().optional(),
  progress: z.number().min(0).max(100),
  clientType: z.enum(["client", "in_house"]),
  description: z.string().optional(),
  clientName: z.string().optional(),
  contactPerson: z.string().optional(),
  deliveryHead: z.string().optional(),
});

export type CreateProjectFormValues = z.infer<typeof createProjectFormSchema>;

export const projectSchema = createProjectFormSchema.extend({
  id: z.string(),
});

export type Project = z.infer<typeof projectSchema>;

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "PRJ-01",
    name: "Appofy",
    code: "APP-01",
    stageGroup: "New",
    stage: "New",
    periodStart: "15 Apr 25",
    periodEnd: "18 Jun 25",
    managerName: "Test RUR",
    managerCode: "AILOITTE-73",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-02",
    name: "pclient 3",
    code: "PCL-03",
    stageGroup: "New",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 May 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 5,
    clientType: "client",
  },
  {
    id: "PRJ-03",
    name: "Smart Watch",
    code: "SMW-01",
    stageGroup: "New",
    stage: "New",
    periodStart: "20 Feb 25",
    periodEnd: "20 Dec 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 2,
    clientType: "client",
  },
  {
    id: "PRJ-04",
    name: "Testing filter for user filter",
    code: "TST-01",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "18 Feb 25",
    periodEnd: "28 Feb 25",
    managerName: "Sahara Acharya",
    managerCode: "EMP39",
    progress: 15,
    clientType: "client",
  },
  {
    id: "PRJ-05",
    name: "Trigger project 2",
    code: "TRG-02",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "08 Jan 25",
    periodEnd: "31 Jan 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-06",
    name: "Trigger Project Notification",
    code: "TRG-NOTI",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 Jun 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 15,
    clientType: "client",
  },
  {
    id: "PRJ-07",
    name: "WorkSync",
    code: "WSC-01",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "24 Apr 25",
    periodEnd: "24 Aug 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-08",
    name: "Pro1",
    code: "PRO-01",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "24 Mar 25",
    periodEnd: "24 Jun 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-09",
    name: "Shopify 12",
    code: "SHP-12",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "21 Feb 25",
    periodEnd: "21 May 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-10",
    name: "client 2",
    code: "CLI-02",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "20 Jan 25",
    periodEnd: "20 Mar 25",
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
    progress: 2,
    clientType: "client",
  },
  {
    id: "PRJ-11",
    name: "Games10",
    code: "GMS-10",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "12 Feb 25",
    periodEnd: "12 Jul 25",
    managerName: "Deepak Rawat",
    managerCode: "EMP25",
    progress: 3,
    clientType: "client",
  },
  // In-House Projects
  {
    id: "PRJ-IH-01",
    name: "Internal ERP Engine",
    code: "ERP-ENG",
    stageGroup: "New",
    stage: "New",
    periodStart: "01 May 25",
    periodEnd: "01 Dec 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 10,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-02",
    name: "Design System & Component Library",
    code: "DS-LIB",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "10 Mar 25",
    periodEnd: "15 Aug 25",
    managerName: "Sahara Acharya",
    managerCode: "EMP39",
    progress: 25,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-03",
    name: "DevOps Pipeline Automation",
    code: "DVP-AUTO",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 Jul 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 45,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-04",
    name: "AI Analytics Dashboard",
    code: "AI-DASH",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "15 Jan 25",
    periodEnd: "15 Jun 25",
    managerName: "Deepak Rawat",
    managerCode: "EMP25",
    progress: 60,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-05",
    name: "Authentication & SSO Gateway",
    code: "SSO-GTW",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "01 Jan 25",
    periodEnd: "01 May 25",
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
    progress: 80,
    clientType: "in_house",
  },
];
