import { z } from "zod";

export const projectStageSchema = z.enum([
  "New",
  "In Discovery",
  "Sprint Planning",
  "In Development",
  "Completed",
]);
export type ProjectStage = z.infer<typeof projectStageSchema>;

export const projectSchema = z.object({
  id: z.string(),
  name: z.string().min(2, "Project name must be at least 2 characters"),
  stageGroup: projectStageSchema,
  stage: z.string(),
  periodStart: z.string(),
  periodEnd: z.string(),
  managerName: z.string(),
  managerCode: z.string(),
  managerAvatar: z.string().optional(),
  progress: z.number().min(0).max(100),
  clientType: z.enum(["client", "in_house"]),
});

export type Project = z.infer<typeof projectSchema>;

export const createProjectFormSchema = projectSchema.omit({
  id: true,
});

export type CreateProjectFormValues = z.infer<typeof createProjectFormSchema>;

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "PRJ-01",
    name: "Appofy",
    stageGroup: "New",
    stage: "New",
    periodStart: "15 Apr 25",
    periodEnd: "18 Jun 25",
    managerName: "Test RUR",
    managerCode: "AILOITTE-73",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-02",
    name: "pclient 3",
    stageGroup: "New",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 May 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 5,
    clientType: "client",
  },
  {
    id: "PRJ-03",
    name: "Smart Watch",
    stageGroup: "New",
    stage: "New",
    periodStart: "20 Feb 25",
    periodEnd: "20 Dec 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 2,
    clientType: "client",
  },
  {
    id: "PRJ-04",
    name: "Testing filter for user filter",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "18 Feb 25",
    periodEnd: "28 Feb 25",
    managerName: "Sahara Acharya",
    managerCode: "EMP39",
    progress: 15,
    clientType: "client",
  },
  {
    id: "PRJ-05",
    name: "Trigger project 2",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "08 Jan 25",
    periodEnd: "31 Jan 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-06",
    name: "Trigger Project Notification",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 Jun 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 15,
    clientType: "client",
  },
  {
    id: "PRJ-07",
    name: "WorkSync",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "24 Apr 25",
    periodEnd: "24 Aug 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-08",
    name: "Pro1",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "24 Mar 25",
    periodEnd: "24 Jun 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-09",
    name: "Shopify 12",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "21 Feb 25",
    periodEnd: "21 May 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-10",
    name: "client 2",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "20 Jan 25",
    periodEnd: "20 Mar 25",
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
    progress: 2,
    clientType: "client",
  },
  {
    id: "PRJ-11",
    name: "Games10",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "12 Feb 25",
    periodEnd: "12 Jul 25",
    managerName: "Deepak Rawat",
    managerCode: "EMP25",
    progress: 3,
    clientType: "client",
  },
];
