import { z } from "zod";

export const projectStageSchema = z.enum([
  "New",
  "In Discovery",
  "Sprint Planning",
  "In Development",
  "In UAT",
  "Released & In Support",
  "In Maintenance",
  "Completed",
  "Closed",
]);
export type ProjectStage = z.infer<typeof projectStageSchema>;

export const teamMemberSchema = z.object({
  id: z.string(),
  name: z.string().min(1, "Name is required"),
  role: z.string().min(1, "Role is required"),
  email: z.string().optional(),
  isTechLead: z.boolean(),
});

export type TeamMember = z.infer<typeof teamMemberSchema>;

export const projectTeamSchema = z.object({
  id: z.string(),
  name: z.string().min(1, "Team name is required"),
  leadName: z.string().optional(),
  description: z.string().optional(),
  members: z.array(teamMemberSchema),
});

export type ProjectTeam = z.infer<typeof projectTeamSchema>;

export const createProjectFormSchema = z.object({
  name: z.string().min(2, "Project name must be at least 2 characters"),
  code: z.string().optional(),
  department: z.string().optional(),
  projectType: z.string().optional(),
  projectStatus: z.string().optional(),
  clientEmail: z.string().optional(),
  secondaryEmails: z.array(z.string()).optional(),
  startTime: z.string().optional(),
  createdBy: z.string().optional(),
  createdAt: z.string().optional(),
  lastUpdated: z.string().optional(),
  stageGroup: projectStageSchema,
  stage: z.string(),
  periodStart: z.string().min(1, "Start Date is required"),
  periodEnd: z.string().min(1, "End Date is required"),
  managerName: z.string().min(1, "Project Manager is required"),
  managerCode: z.string(),
  managerAvatar: z.string().optional(),
  progress: z.number().min(0).max(100),
  clientType: z.enum(["client", "in_house"]),
  description: z.string().optional(),
  clientName: z.string().optional(),
  contactPerson: z.string().optional(),
  deliveryHead: z.string().optional(),
  teamMembers: z.array(teamMemberSchema).optional(),
  teams: z.array(projectTeamSchema).optional(),
});

export type CreateProjectFormValues = z.infer<typeof createProjectFormSchema>;

export const projectSchema = createProjectFormSchema.extend({
  id: z.string(),
});

export type Project = z.infer<typeof projectSchema>;

export interface UserRoleProfile {
  id: string;
  name: string;
  code: string;
  role: "admin" | "pm";
  email: string;
  avatar: string;
}

export const USER_PROFILES: UserRoleProfile[] = [
  {
    id: "usr-admin",
    name: "Lead Engineer",
    code: "ADMIN",
    role: "admin",
    email: "admin@project-epd.io",
    avatar: "EP",
  },
  {
    id: "usr-vikas",
    name: "Vikas Singh",
    code: "AILOITTE-45",
    role: "pm",
    email: "vikas.singh@ailoitte.com",
    avatar: "VS",
  },
  {
    id: "usr-sahara",
    name: "Sahara Acharya",
    code: "EMP39",
    role: "pm",
    email: "sahara.a@ailoitte.com",
    avatar: "SA",
  },
  {
    id: "usr-dehradun",
    name: "Dehradun Kumar",
    code: "EMP40",
    role: "pm",
    email: "dehradun.k@ailoitte.com",
    avatar: "DK",
  },
  {
    id: "usr-rahul",
    name: "Rahul Yadav",
    code: "AILOITTE-89",
    role: "pm",
    email: "rahul.yadav@ailoitte.com",
    avatar: "RY",
  },
];

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "prj-01",
    name: "Alpha Vision Segmentation",
    code: "PRJ-001",
    department: "Data Processing",
    projectType: "Data Annotation",
    projectStatus: "IN_PROGRESS",
    stageGroup: "In Development",
    stage: "IN_PROGRESS",
    periodStart: "2026-08-01",
    periodEnd: "2026-12-31",
    managerName: "Vikram Malhotra",
    managerCode: "EMP-102",
    progress: 45,
    clientType: "client",
    clientName: "BioTech Global Corp",
    clientEmail: "biotech.client@biotech-global.com",
    secondaryEmails: ["ops@biotech-global.com", "delivery@biotech-global.com"],
    description:
      "High-density medical image segmentation and cellular boundaries tagging.",
    startTime: "09:00",
    createdBy: "Vikram Malhotra",
    createdAt: "Aug 1, 2026, 02:30 PM",
    lastUpdated: "Aug 25, 2026, 07:30 PM",
  },
  {
    id: "PRJ-01",
    name: "Appofy",
    code: "APP-01",
    department: "Engineering & Product",
    stageGroup: "New",
    stage: "New",
    periodStart: "15 Apr 25",
    periodEnd: "18 Jun 25",
    managerName: "Test RUR",
    managerCode: "AILOITTE-73",
    progress: 0,
    clientType: "client",
    teamMembers: [
      {
        id: "tm-1",
        name: "Amit Sharma",
        role: "Senior Fullstack Engineer",
        email: "amit@ailoitte.com",
        isTechLead: true,
      },
      {
        id: "tm-2",
        name: "Pooja Verma",
        role: "Frontend Developer",
        email: "pooja@ailoitte.com",
        isTechLead: false,
      },
    ],
    teams: [
      {
        id: "team-1",
        name: "Frontend Web Team",
        leadName: "Amit Sharma",
        description: "Next.js & Tailwind CSS UI Development",
        members: [
          {
            id: "tm-1",
            name: "Amit Sharma",
            role: "Senior Fullstack Engineer",
            email: "amit@ailoitte.com",
            isTechLead: true,
          },
          {
            id: "tm-2",
            name: "Pooja Verma",
            role: "Frontend Developer",
            email: "pooja@ailoitte.com",
            isTechLead: false,
          },
        ],
      },
      {
        id: "team-2",
        name: "Backend Core API Team",
        leadName: "Rahul Verma",
        description: "Node.js Microservices & DB Architecture",
        members: [
          {
            id: "tm-10",
            name: "Rahul Verma",
            role: "Backend Architect",
            email: "rahul.v@ailoitte.com",
            isTechLead: true,
          },
        ],
      },
    ],
  },
  {
    id: "PRJ-02",
    name: "pclient 3",
    code: "PCL-03",
    department: "Engineering & Product",
    stageGroup: "New",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 May 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 5,
    clientType: "client",
    teamMembers: [
      {
        id: "tm-3",
        name: "Rohan Gupta",
        role: "Tech Lead",
        email: "rohan@ailoitte.com",
        isTechLead: true,
      },
      {
        id: "tm-4",
        name: "Sneha Patel",
        role: "UI/UX Designer",
        email: "sneha@ailoitte.com",
        isTechLead: false,
      },
    ],
    teams: [
      {
        id: "team-3",
        name: "Design & UX Team",
        leadName: "Sneha Patel",
        description: "UI System & Wireframes",
        members: [
          {
            id: "tm-4",
            name: "Sneha Patel",
            role: "UI/UX Designer",
            email: "sneha@ailoitte.com",
            isTechLead: true,
          },
        ],
      },
      {
        id: "team-4",
        name: "Engineering & QA",
        leadName: "Rohan Gupta",
        description: "Product Development & Testing",
        members: [
          {
            id: "tm-3",
            name: "Rohan Gupta",
            role: "Tech Lead",
            email: "rohan@ailoitte.com",
            isTechLead: true,
          },
        ],
      },
    ],
  },
  {
    id: "PRJ-03",
    name: "Smart Watch",
    code: "SMW-01",
    department: "Engineering & Product",
    stageGroup: "New",
    stage: "New",
    periodStart: "20 Feb 25",
    periodEnd: "20 Dec 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 2,
    clientType: "client",
    teamMembers: [
      {
        id: "tm-5",
        name: "Karan Johar",
        role: "Embedded Systems Developer",
        email: "karan@ailoitte.com",
        isTechLead: true,
      },
    ],
  },
  {
    id: "PRJ-04",
    name: "Testing filter for user filter",
    code: "TST-01",
    department: "Quality Assurance",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "18 Feb 25",
    periodEnd: "28 Feb 25",
    managerName: "Sahara Acharya",
    managerCode: "EMP39",
    progress: 15,
    clientType: "client",
  },
  {
    id: "PRJ-05",
    name: "Trigger project 2",
    code: "TRG-02",
    department: "Engineering & Product",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "08 Jan 25",
    periodEnd: "31 Jan 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-06",
    name: "Trigger Project Notification",
    code: "TRG-NOTI",
    department: "Engineering & Product",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 Jun 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 15,
    clientType: "client",
  },
  {
    id: "PRJ-07",
    name: "WorkSync",
    code: "WSC-01",
    department: "Engineering & Product",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "24 Apr 25",
    periodEnd: "24 Aug 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-08",
    name: "Pro1",
    code: "PRO-01",
    department: "Engineering & Product",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "24 Mar 25",
    periodEnd: "24 Jun 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-09",
    name: "Shopify 12",
    code: "SHP-12",
    department: "E-Commerce",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "21 Feb 25",
    periodEnd: "21 May 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 0,
    clientType: "client",
  },
  {
    id: "PRJ-10",
    name: "client 2",
    code: "CLI-02",
    department: "Engineering & Product",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "20 Jan 25",
    periodEnd: "20 Mar 25",
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
    progress: 2,
    clientType: "client",
  },
  {
    id: "PRJ-11",
    name: "Games10",
    code: "GMS-10",
    department: "Gaming & AI",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "12 Feb 25",
    periodEnd: "12 Jul 25",
    managerName: "Deepak Rawat",
    managerCode: "EMP25",
    progress: 35,
    clientType: "client",
  },
  {
    id: "PRJ-12",
    name: "HealthTrack Mobile",
    code: "HTM-01",
    department: "Mobile Engineering",
    stageGroup: "In UAT",
    stage: "New",
    periodStart: "01 Jan 25",
    periodEnd: "30 Apr 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 85,
    clientType: "client",
  },
  {
    id: "PRJ-13",
    name: "FinTech Gateway",
    code: "FTG-02",
    department: "Finance & Operations",
    stageGroup: "Released & In Support",
    stage: "New",
    periodStart: "15 Oct 24",
    periodEnd: "15 Mar 25",
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
    progress: 95,
    clientType: "client",
  },
  {
    id: "PRJ-14",
    name: "E-Commerce Portal V2",
    code: "ECP-02",
    department: "Engineering & Product",
    stageGroup: "In Maintenance",
    stage: "New",
    periodStart: "01 Aug 24",
    periodEnd: "01 Jan 25",
    managerName: "Sahara Acharya",
    managerCode: "EMP39",
    progress: 100,
    clientType: "client",
  },
  {
    id: "PRJ-15",
    name: "Legacy CRM Migration",
    code: "CRM-LEG",
    department: "Engineering & Product",
    stageGroup: "Closed",
    stage: "New",
    periodStart: "01 Jan 24",
    periodEnd: "31 Dec 24",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 100,
    clientType: "client",
  },
  // In-House Projects
  {
    id: "PRJ-IH-01",
    name: "Internal ERP Engine",
    code: "ERP-ENG",
    department: "Engineering & Product",
    stageGroup: "New",
    stage: "New",
    periodStart: "01 May 25",
    periodEnd: "01 Dec 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 10,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-02",
    name: "Design System & Component Library",
    code: "DS-LIB",
    department: "Design & UX",
    stageGroup: "In Discovery",
    stage: "New",
    periodStart: "10 Mar 25",
    periodEnd: "15 Aug 25",
    managerName: "Sahara Acharya",
    managerCode: "EMP39",
    progress: 25,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-03",
    name: "DevOps Pipeline Automation",
    code: "DVP-AUTO",
    department: "DevOps & Cloud",
    stageGroup: "Sprint Planning",
    stage: "New",
    periodStart: "01 Feb 25",
    periodEnd: "30 Jul 25",
    managerName: "Dehradun Kumar",
    managerCode: "EMP40",
    progress: 45,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-04",
    name: "AI Analytics Dashboard",
    code: "AI-DASH",
    department: "AI & Data Science",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "15 Jan 25",
    periodEnd: "15 Jun 25",
    managerName: "Deepak Rawat",
    managerCode: "EMP25",
    progress: 60,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-05",
    name: "Authentication & SSO Gateway",
    code: "SSO-GTW",
    department: "Security & IAM",
    stageGroup: "In Development",
    stage: "New",
    periodStart: "01 Jan 25",
    periodEnd: "01 May 25",
    managerName: "Rahul Yadav",
    managerCode: "AILOITTE-89",
    progress: 80,
    clientType: "in_house",
  },
  {
    id: "PRJ-IH-06",
    name: "Internal Knowledge Base Bot",
    code: "KBB-01",
    department: "AI & Data Science",
    stageGroup: "In UAT",
    stage: "New",
    periodStart: "15 Nov 24",
    periodEnd: "30 Mar 25",
    managerName: "Vikas Singh",
    managerCode: "AILOITTE-45",
    progress: 90,
    clientType: "in_house",
  },
];
